manifest:
  self:
    path: app
    west-commands: scripts/west-commands.yml
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
############################################################################################
# Uncomment and remove previous `remotes` and `projects` to configure the project with ncs #
############################################################################################
# remotes:
#   - name: ncs
#     url-base: https://github.com/nrfconnect
# projects:
#   - name: nrf
#     remote: ncs
#     repo-path: sdk-nrf
#     revision: v2.3.0
#     import: true
